### ISSUE TITLE
[talosintel_ipfilter]: Pulling from the Wrong URL

### ISSUE THREAD

**Issue by finchy** [ktsaou/blocklist-ipsets#2]
Sorry, I think I gave you the wrong feed before, that's my fault, and we'll fix it.

http://talosintel.com/feeds/ip-filter.blf is the correct feed.

**Comment by ktsaou** [comment]
thanks! I updated it.
I update it every 4 hours. How often do you generate this file?

**Comment by finchy** [comment]
Every 15 minutes.

**Comment by ktsaou** [comment]
I now download it every 15 mins (it will show on the site on the next content change of your list).

Thank you for your support!

If you want me to add some additional info for your list, please let know.
The `about` section now shows just this:

```
List of known malicious network threats
```

It would be perfect if we could have a better description. How you collect these IPs, if you cross check them with any other lists, what do you do to eliminate false positives, how do you protect the list from being poisoned (i.e. is it possible for attackers to have third party IPs listed), etc.

Also, if you have any third party publicly available IP lists to suggest, please let me know.

Of course, I am also open for any suggestion, of any kind...

**Comment by ktsaou** [comment]
@finchy the FireHOL IP Lists site has been moved to http://iplists.firehol.org/

If you link to the old URL, please update it. If not, I would be grateful if you add a link to it, at your site.

Your list is here

http://iplists.firehol.org/?ipset=talosintel_ipfilter

**Comment by ktsaou** [comment]
I am closing this issue, since the URL has been updated.
If any issue remains, please re-open it.
